/laserMapping:
  ros__parameters:
    common:
      img_topic: "/camera/image_raw"
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: true

    extrin_calib:
      extrinsic_T: [-0.011, -0.02329, -0.04412]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      Rcl: [0.0, -1.0, 0.0,
            0.374607, 0.0, -0.927184,
            0.927184, 0.0, 0.374607]
      Pcl: [0.0, -0.08, -0.02]

    time_offset: 
      imu_time_offset: 0.0
      img_time_offset: 0.0
      exposure_time_init: 0.0

    preprocess:
      point_filter_num: 2
      filter_size_surf: 0.15
      lidar_type: 1 # Livox Avia / Mid-360 CustomMsg
      scan_line: 4
      blind: 0.2

    vio:
      max_iterations: 5
      outlier_threshold: 150.0
      img_point_cov: 100.0
      patch_size: 8
      patch_pyrimid_level: 2
      normal_en: true
      raycast_en: false
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 100
      acc_cov: 0.5
      gyr_cov: 0.3
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001

    lio:
      max_iterations: 5
      dept_err: 0.02
      beam_err: 0.05
      min_eigen_value: 0.0025
      voxel_size: 0.5
      max_layer: 2
      max_points_num: 50
      layer_init_num: [5, 5, 5, 5, 5]

    local_map:  
      map_sliding_en: true
      half_map_size: 50
      sliding_thresh: 5

    uav:
      imu_rate_odom: false
      gravity_align_en: true

    publish:
      dense_map_en: false
      pub_effect_point_en: false 
      pub_plane_en: false
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "Zenith_Flight"
      pose_output_en: false

    pcd_save:
      pcd_save_en: true
      colmap_output_en: false
      filter_size_pcd: 0.02
      interval: -1
